/**
 * Design Theme for ONDC Logistics BAP
 * Cream white + Orange primary with soft neumorphism
 */

export const theme = {
    colors: {
        background: '#FFF7ED',
        surface: '#FFFFFF',
        surfaceAlt: '#FFF0DE',
        primary: '#F97316',
        primaryDark: '#EA580C',
        primaryLight: '#FDBA74',
        primaryGhost: '#FFF7ED',
        secondary: '#0EA5E9',
        secondaryLight: '#BAE6FD',
        text: '#1C1917',
        textSecondary: '#78716C',
        textMuted: '#A8A29E',
        textOnPrimary: '#FFFFFF',
        success: '#22C55E',
        successLight: '#DCFCE7',
        error: '#EF4444',
        errorLight: '#FEE2E2',
        warning: '#F59E0B',
        warningLight: '#FEF3C7',
        border: '#E7E5E4',
        borderLight: '#F5F5F4',
        shadow: '#292524',
        overlay: 'rgba(28, 25, 23, 0.5)',
        cardShadow: 'rgba(249, 115, 22, 0.08)',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    borderRadius: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        full: 9999,
    },
    fontSize: {
        xs: 11,
        sm: 13,
        md: 15,
        lg: 18,
        xl: 22,
        xxl: 28,
        hero: 34,
    },
    fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
    },
    shadow: {
        sm: {
            shadowColor: '#292524',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 2,
            elevation: 1,
        },
        md: {
            shadowColor: '#292524',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 8,
            elevation: 3,
        },
        lg: {
            shadowColor: '#292524',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.12,
            shadowRadius: 16,
            elevation: 6,
        },
        neumorphic: {
            shadowColor: '#D6D3D1',
            shadowOffset: { width: 4, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 4,
        },
    },
};
